ALTER TABLE "FiscalPeriod" ADD COLUMN IF NOT EXISTS "year" INTEGER;
UPDATE "FiscalPeriod" SET "year" = EXTRACT(YEAR FROM "startDate") WHERE "year" IS NULL;
UPDATE "FiscalPeriod" SET "year" = 2026 WHERE "year" IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "FiscalPeriod_year_key" ON "FiscalPeriod"("year");
ALTER TABLE "FiscalPeriod" ADD COLUMN IF NOT EXISTS "closedAt" TIMESTAMP(3);

ALTER TABLE "ExportJob" ADD COLUMN IF NOT EXISTS "entityType" TEXT DEFAULT 'GENERAL';
ALTER TABLE "ExportJob" ADD COLUMN IF NOT EXISTS "entityId" TEXT;
ALTER TABLE "ExportJob" ADD COLUMN IF NOT EXISTS "requestedAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "PrintPreference" ADD COLUMN IF NOT EXISTS "includeLetterheadByDefault" BOOLEAN DEFAULT true;
